First version
edhirama/MovieAddiction pull request #1
Opened 2018-11-29 01:05 UTC by edhirama

First version of the project. 
Still missing error handling and tests.

2018-12-05 16:45 UTC, ghost requested changes

2018-12-05 16:45 UTC, ghost commented on MovieAddiction/MovieAddiction/AppDelegate.swift
> +    func applicationWillResignActive(_ application: UIApplication) {
What do you think about removing all these boilerplate code?

2018-12-05 16:45 UTC, ghost commented on MovieAddiction/MovieAddiction/Modules/UpcomingMovies/Cells/UpcomingMoviesTableViewCell.xib
> +                <outlet property="posterImageView" destination="6CE-23-Fl7" id="W0t-ir-ZB6"/>
Have you noticed these broken constraints?

```
Make a symbolic breakpoint at UIViewAlertForUnsatisfiableConstraints to catch this in the debugger.
The methods in the UIConstraintBasedLayoutDebugging category on UIView listed in <UIKitCore/UIView.h> may also be helpful.
2018-12-05 13:29:05.696528-0200 MovieAddiction[38865:1266867] [LayoutConstraints] Unable to simultaneously satisfy constraints.
	Probably at least one of the constraints in the following list is one you don't want. 
	Try this: 
		(1) look at each constraint and try to figure out which you don't expect; 
		(2) find the code that added the unwanted constraint or constraints and fix it. 
(
    "<NSLayoutConstraint:0x7fdd2b13b110 UIImageView:0x7fdd2b11b480.width == 0.666667*UIImageView:0x7fdd2b11b480.height   (active)>",
    "<NSLayoutConstraint:0x7fdd29d3c7a0 V:|-(0)-[UIImageView:0x7fdd2b11b480]   (active, names: '|':UIView:0x7fdd2b11b290 )>",
    "<NSLayoutConstraint:0x7fdd29d53aa0 UIImageView:0x7fdd2b11b480.centerY == UIView:0x7fdd2b11b290.centerY   (active)>",
    "<NSLayoutConstraint:0x7fdd2b206b80 UIImageView:0x7fdd2b11b480.width == 0.2*UITableViewCellContentView:0x7fdd2b11b090.width   (active)>",
    "<NSLayoutConstraint:0x7fdd2b206cc0 UIView:0x7fdd2b11b290.top == UITableViewCellContentView:0x7fdd2b11b090.topMargin + 16   (active)>",
    "<NSLayoutConstraint:0x7fdd2b206d70 UITableViewCellContentView:0x7fdd2b11b090.bottomMargin == UIView:0x7fdd2b11b290.bottom + 16   (active)>",
    "<NSLayoutConstraint:0x7fdd2b20ba00 'UIView-bottomMargin-guide-constraint' V:[UILayoutGuide:0x7fdd2b20b650'UIViewLayoutMarginsGuide']-(8)-|   (active, names: '|':UITableViewCellContentView:0x7fdd2b11b090 )>",
    "<NSLayoutConstraint:0x7fdd2b11d120 'UIView-Encapsulated-Layout-Height' UITableViewCellContentView:0x7fdd2b11b090.height == 160.667   (active)>",
    "<NSLayoutConstraint:0x7fdd2b11d0c0 'UIView-Encapsulated-Layout-Width' UITableViewCellContentView:0x7fdd2b11b090.width == 375   (active)>",
    "<NSLayoutConstraint:0x7fdd2b20b780 'UIView-topMargin-guide-constraint' V:|-(8)-[UILayoutGuide:0x7fdd2b20b650'UIViewLayoutMarginsGuide']   (active, names: '|':UITableViewCellContentView:0x7fdd2b11b090 )>"
)

Will attempt to recover by breaking constraint 
<NSLayoutConstraint:0x7fdd2b13b110 UIImageView:0x7fdd2b11b480.width == 0.666667*UIImageView:0x7fdd2b11b480.height   (active)>
```

2018-12-05 16:45 UTC, ghost commented on MovieAddiction/MovieAddiction/Models/Movie.swift
> +        case voteAverage = "vote_average"
How about decode it using snake case strategy?

https://www.hackingwithswift.com/articles/52/swift-4-1-improves-codable-with-keydecodingstrategy

2018-12-05 16:45 UTC, ghost commented on MovieAddiction/MovieAddiction/Modules/UpcomingMovies/Cells/UpcomingMoviesTableViewCell.swift
> +    @IBOutlet weak var posterImageView: UIImageView!
Could it be private?

2018-12-05 16:45 UTC, ghost commented on MovieAddiction/MovieAddiction/Network/Services/UpcomingMoviesService.swift
> +        let queryItems = [URLQueryItem(name: TMDbURL.Movie.ParameterKey.apiKey.rawValue, value: "1f54bd990f1cdfb230adb312546d765d"),
How could it be safer and reusable?

2018-12-05 16:45 UTC, ghost commented on MovieAddiction/MovieAddiction/Modules/UpcomingMovies/UpcomingMoviesViewController.swift
> +    let imageCache = NSCache<NSString, UIImage>()
Do you think it is a good idea to keep cache control in the controller layer? If you think it could be different, how would you do it?

2018-12-05 16:45 UTC, ghost commented on MovieAddiction/MovieAddiction/ViewModels/UpcomingMoviesViewModel.swift
> +    func filter(forSearchText searchText: String, scope: String = "All") {
`scope: String = "All"` What is it?

2018-12-05 16:45 UTC, ghost commented on MovieAddiction/MovieAddiction/ViewModels/UpcomingMoviesViewModel.swift
> +        self.isFiltering = true
Do you think it is necessary to use `self.` here?

2018-12-05 16:45 UTC, arctouch-andersongusmao commented on MovieAddiction/MovieAddiction/ViewModels/UpcomingMoviesViewModel.swift
> +    private var movies = [Movie]()
Why the ViewModel is keeping three arrays, i.e. `private var movies = [Movie](), private var moviesViewModels = [MovieViewModel](), private var filteredMovies = [Movie]()` ?  Is it correct from your point of view?  How could you do it differently?

2018-12-05 16:45 UTC, arctouch-andersongusmao commented on MovieAddiction/MovieAddiction/ViewModels/UpcomingMoviesViewModel.swift
> +                DispatchQueue.main.async {
Could it potentially lead into a retain cycle?

2018-12-05 16:45 UTC, arctouch-andersongusmao commented on MovieAddiction/MovieAddiction/Modules/UpcomingMovies/UpcomingMoviesViewController.swift
> +    let searchController = UISearchController(searchResultsController: nil)
Have you noticed this leak? Do you have some clue how to solve? 

![screen shot 2018-12-05 at 14 19 52](https://user-images.githubusercontent.com/37085255/49527383-ef66a880-f898-11e8-83e7-32af5630b7dd.png)

2018-12-05 16:45 UTC, arctouch-andersongusmao commented on MovieAddiction/MovieAddiction/Modules/UpcomingMovies/UpcomingMoviesViewController.swift
> +class UpcomingMoviesViewController: UIViewController {
Do you think it is a good idea to make it final? Do you have some advantage doing that?

2018-12-05 16:45 UTC, arctouch-andersongusmao commented on MovieAddiction/MovieAddiction/Base.lproj/Main.storyboard
> +                <navigationController id="Who-nD-SEG" sceneMemberID="viewController">
If you are using `navigationController ` why did not you push your detail view controller?

2018-12-05 16:45 UTC, arctouch-andersongusmao commented on MovieAddiction/MovieAddiction/Modules/MovieDetails/MovieDetailViewController.swift
> +    func configureView() {
does it make sense to this method to have public visibility?

2018-12-05 16:45 UTC, arctouch-andersongusmao commented on MovieAddiction/MovieAddiction/Network/Services/UpcomingMoviesService.swift
> +class UpcomingMoviesService {
If you are asked to create some unit tests for this, how could you accomplish it?

2018-12-06 00:34 UTC, edhirama commented on MovieAddiction/MovieAddiction/AppDelegate.swift
> +    func applicationWillResignActive(_ application: UIApplication) {
I’ve never thought about removing the AppDelegate boilerplate code, I think it is a good idea to keep it clear what methods are being used so far. Will do.

2018-12-06 00:34 UTC, edhirama commented on MovieAddiction/MovieAddiction/Modules/UpcomingMovies/Cells/UpcomingMoviesTableViewCell.xib
> +                <outlet property="posterImageView" destination="6CE-23-Fl7" id="W0t-ir-ZB6"/>
Yes, but I didn’t have time to resolve it.

2018-12-06 00:34 UTC, edhirama commented on MovieAddiction/MovieAddiction/Models/Movie.swift
> +        case voteAverage = "vote_average"
That’s nice, I didn’t know this approach. Will do.

2018-12-06 00:36 UTC, edhirama commented on MovieAddiction/MovieAddiction/Modules/UpcomingMovies/Cells/UpcomingMoviesTableViewCell.swift
> +    @IBOutlet weak var posterImageView: UIImageView!
Right now it couldn't because I set the image outside the scope of the cell. But it can be improved, and I will when I refactor the image caching strategy. Thanks!

2018-12-06 00:37 UTC, edhirama commented on MovieAddiction/MovieAddiction/Network/Services/UpcomingMoviesService.swift
> +        let queryItems = [URLQueryItem(name: TMDbURL.Movie.ParameterKey.apiKey.rawValue, value: "1f54bd990f1cdfb230adb312546d765d"),
By creating a build configuration. I honestly just didn’t put that in my priorities, sorry about that. Will do.

2018-12-06 00:38 UTC, edhirama commented on MovieAddiction/MovieAddiction/Modules/UpcomingMovies/UpcomingMoviesViewController.swift
> +    let imageCache = NSCache<NSString, UIImage>()
No, it’s definitely not. I was in a rush because it was the first time that I’ve tried loading images without AlamofireImage and I noticed this weird behavior that the image was reloading on scroll. I think it should not be in the view model as well, since it shouldn’t know about the UIKit. I guess I would make a more complete ImageHelper to help handling it.

2018-12-06 00:39 UTC, edhirama commented on MovieAddiction/MovieAddiction/ViewModels/UpcomingMoviesViewModel.swift
> +    func filter(forSearchText searchText: String, scope: String = "All") {
That’s my mistake. I was kind of following Ray Wenderlich’s tutorial to remember how it’s done and left an unused code. https://www.raywenderlich.com/472-uisearchcontroller-tutorial-getting-started

2018-12-06 00:39 UTC, edhirama commented on MovieAddiction/MovieAddiction/ViewModels/UpcomingMoviesViewModel.swift
> +        self.isFiltering = true
No, it’s not. I’m trying to give up this habit to use when not needed.

2018-12-06 00:40 UTC, edhirama commented on MovieAddiction/MovieAddiction/ViewModels/UpcomingMoviesViewModel.swift
> +                DispatchQueue.main.async {
Yes, I should’ve used the capture list in this one. Will do

2018-12-06 00:41 UTC, edhirama commented on MovieAddiction/MovieAddiction/Modules/UpcomingMovies/UpcomingMoviesViewController.swift
> +    let searchController = UISearchController(searchResultsController: nil)
No, I haven’t. Just by looking at it I can only tell that it's something view related, but that's all. If you could give a better clue that would be nice, please.

2018-12-06 00:42 UTC, edhirama commented on MovieAddiction/MovieAddiction/Modules/UpcomingMovies/UpcomingMoviesViewController.swift
> +class UpcomingMoviesViewController: UIViewController {
I think it so because then no one could inherit from this view controller. But I'm not sure if there's another advantage other than that, honestly.

2018-12-06 00:42 UTC, edhirama commented on MovieAddiction/MovieAddiction/Base.lproj/Main.storyboard
> +                <navigationController id="Who-nD-SEG" sceneMemberID="viewController">
I started up doing as navigation controller flow, but I changed because I wanted to create a transition animation. But I didn’t have time to do it nor did the clean up in the code.

2018-12-06 00:42 UTC, edhirama commented on MovieAddiction/MovieAddiction/Modules/MovieDetails/MovieDetailViewController.swift
> +    func configureView() {
No, it doesn’t. Will change.

2018-12-06 01:03 UTC, edhirama commented on MovieAddiction/MovieAddiction/ViewModels/UpcomingMoviesViewModel.swift
> +    private var movies = [Movie]()
Actually it's keeping four arrays, there's the filteredMoviesViewModels, too. Clearly it's not the best way. Probably with only one array of movies and one of their view models. I could chain the map and filter to update the view models array when in filtering mode, but could reset it back to mapping the movies objects when cancelling the search.

2018-12-06 01:29 UTC, edhirama commented on MovieAddiction/MovieAddiction/Network/Services/UpcomingMoviesService.swift
> +class UpcomingMoviesService {
I don't have experience working with tests for the network layer, but I guess I would have to mock the request somehow in order to check if it returns error or the parsed results.

2018-12-06 01:30 UTC, edhirama commented on MovieAddiction/MovieAddiction/Network/Services/UpcomingMoviesService.swift
> +class UpcomingMoviesService {
Thanks for all the feedback! Really appreciate it.

2020-09-28 23:27 UTC, merged